# REFERENCE: https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: https://npm.pkg.github.com

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${GH_PAT}

  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

  //registry.yarnpkg.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

npmRegistryServer: https://registry.yarnpkg.com

npmScopes:
  flex-development:
    npmRegistryServer: https://npm.pkg.github.com

plugins:
# throws `Reference Error: _a is not defined (when initializing
# @yarnpkg/plugin-interactive-tools, defined in /xxx/.yarnrc.yml)`
# when using ts-node > v10.7.0
# - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
#   spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.1.cjs
